name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the project
      run: cargo build --verbose
    - name: Perform static analysis
      run: cargo clippy --verbose
    - name: Run unit tests
      run: cargo test --verbose
